bugfix/send props to google
abdolence/sbt-gcs-resolver pull request #8
Opened 2022-06-24 17:17 UTC by 987Nabil

- Impl. `getOutputStream` for `GcsArtifactRegistryUrlConnection` (#6)
- SBT v1.6.2. Updated Google GCS library to 2.8.0 (#7)
- Ver up
- Bugfix: Save props (headers) when setting and add to the Google request

2022-06-24 18:11 UTC, 987Nabil commented
@abdolence This makes a) sure that all props are send as header and b) the props throw an exception when called after `connected == true`

2022-06-25 12:25 UTC, abdolence requested changes
Thanks for the additions. Have some suggestions to improve this, have a look at the comments.

2022-06-25 12:25 UTC, abdolence commented on sbt-gcs-plugin/src/main/scala/org/latestbit/sbt/gcs/artifactregistry/GcsArtifactRegistryUrlConnection.scala
> +  private var props: Map[String, String] = Map.empty
It seems HttpURLConnection/URLConnection from JVM already has the map, so there is no need to repeat that here I think?

2022-06-25 12:25 UTC, abdolence commented on sbt-gcs-plugin/src/main/scala/org/latestbit/sbt/gcs/artifactregistry/GcsArtifactRegistryUrlConnection.scala
> +            .setHeaders( props.foldLeft( request.getHeaders ) { case ( h, ( k, v ) ) => h.set( k, v ) } )
So, here we can just read `public Map<String,List<String>> getRequestProperties()` instead

2022-06-25 12:25 UTC, abdolence commented on sbt-gcs-plugin/src/main/scala/org/latestbit/sbt/gcs/artifactregistry/GcsArtifactRegistryUrlConnection.scala
> +  override def setRequestProperty( key: String, value: String ): Unit = {
No need to implement if we rely on base Map

2022-06-25 12:29 UTC, abdolence commented on sbt-gcs-plugin/src/main/scala/org/latestbit/sbt/gcs/artifactregistry/GcsArtifactRegistryUrlConnection.scala
> +            .setHeaders( props.foldLeft( request.getHeaders ) { case ( h, ( k, v ) ) => h.set( k, v ) } )
We need to read this Map before connect though since the base implementation checks it.

2022-06-25 12:35 UTC, abdolence commented on sbt-gcs-plugin/src/main/scala/org/latestbit/sbt/gcs/artifactregistry/GcsArtifactRegistryUrlConnection.scala
> +  private final val genericUrl           = GcsArtifactRegistryGenericUrlFactory.createFromUrl( url )
Please use `sbt scalafmt` for formatting to avoid this kind of changes :)

2022-06-25 12:56 UTC, abdolence commented
I've created this PR instead. 
https://github.com/abdolence/sbt-gcs-resolver/pull/9
Please have a look if this is something you are after.

The reasons:
- Support all of the ops, not just put
- Having a Map[] of ready to use HTTP headers instead
- Using `foreach` instead of fold to show it has side effects
- Not to reimplement setRequestProperty

2022-06-25 13:36 UTC, closed without merging

2022-07-14 08:55 UTC, 987Nabil commented
Sorry, I somehow missed the comments. Else I would have responded. I think there might be a problem with your suggestions, but I'll check the other pr